name: macos-build

on:
  gollum:
  workflow_dispatch:
env:
  UPLOAD_BESULT_DIR: true
  GH_TOKEN: ${{ secrets.GT }}
jobs:
  start:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm install
          npm rum electron:build
          ls
      - uses: actions/upload-artifact@master
        with:
          name: result
          path: ./release/iptvnator*
