name: windows-build

on:
  gollum:
  workflow_dispatch:
env:
  UPLOAD_BESULT_DIR: true
jobs:
  start:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: "12.x"
      - name: Run install
          run: npm install
      - name: Run build
          run: npm run build:prod
      - name: Upload result file
          uses: actions/upload-artifact@master
          if: env.UPLOAD_BESULT_DIR == 'true'
          with:
            name: result
            path: ./release/iptvnator*
